### ISSUE TITLE
[Bug] Deep Aether (1.20.1-1.0.4) Stratus Armor causing server crash in Medieval MC [FORGE] - MMC4 modpack

### ISSUE THREAD

**Issue by TonyS-dev** [TunefulTurnip/Deep-Aether#199]
### Forge/Neoforge Version

Forge Version: 47.3.7

### Deep Aether Version

Deep Aether Mod Version: 1.20.1-1.0.4

### Terrablender Version

TerraBlender-forge-1.20.1-3.0.1.7.jar

### Aether Version

aether-1.20.1-1.4.2-neoforge.jar

### Log Files

net.minecraft.ReportedException: Colliding entity with block
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.mixinextras$bridge$m_9240_$157(ServerGamePacketListenerImpl.java)
	at TRANSFORMER/neruina@2.1.2/com.bawnorton.neruina.handler.TickHandler.safelyTickPlayer(TickHandler.java:122)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.wrapOperation$den000$neruina$catchTickingPlayer$notTheCauseOfTickLag(ServerGamePacketListenerImpl.java:6794)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.AbstractMethodError: Receiver class teamrazor.deepaether.item.gear.DaArmorMaterials does not define or inherit an implementation of the resolved method 'abstract java.lang.String m_6082_()' of interface net.minecraft.world.item.ArmorMaterial.
	at TRANSFORMER/deeperdarker@1.3.1/com.kyanite.deeperdarker.DeeperDarkerEvents.livingDamageEvent(DeeperDarkerEvents.java:145)
	at TRANSFORMER/deeperdarker@1.3.1/com.kyanite.deeperdarker.__DeeperDarkerEvents_livingDamageEvent_LivingDamageEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.7/net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:298)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_6475_(Player.java:912)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1112)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_6469_(Player.java:840)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_6469_(ServerPlayer.java:695)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.BaseFireBlock.m_7892_(BaseFireBlock.java:119)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60682_(BlockBehaviour.java:766)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20101_(Entity.java:998)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_146872_(Entity.java:773)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_6478_(Entity.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_21074_(LivingEntity.java:2195)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_7023_(LivingEntity.java:2132)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_7023_(Player.java:1423)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2605)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8107_(Player.java:501)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:241)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
	... 12 more

## Description
The Deep Aether mod's (version 1.20.1-1.0.4) Stratus Armor is causing a server crash in the Medieval MC [FORGE] - MMC4 modpack due to an incomplete implementation of the `ArmorMaterial` interface. This results in Neruina kicking players due to a ticking exception when damage calculations are attempted.

## Environment
- Modpack: Medieval MC [FORGE] - MMC4
- Server Type: Dedicated Server (not single player)
- Minecraft Version: 1.20.1
- Forge Version: 47.3.7
- Deep Aether Mod Version: 1.20.1-1.0.4
- Neruina Version: 2.1.2
- Deeper and Darker Version: 1.3.1

## Error Log
```
net.minecraft.ReportedException: Colliding entity with block
    at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530)
    ...
Caused by: java.lang.AbstractMethodError: Receiver class teamrazor.deepaether.item.gear.DaArmorMaterials does not define or inherit an implementation of the resolved method 'abstract java.lang.String m_6082_()' of interface net.minecraft.world.item.ArmorMaterial.
    at TRANSFORMER/deeperdarker@1.3.1/com.kyanite.deeperdarker.DeeperDarkerEvents.livingDamageEvent(DeeperDarkerEvents.java:145)
    ...
```

## Steps to Reproduce
1. Set up a dedicated server using the Medieval MC [FORGE] - MMC4 modpack
2. Ensure Deep Aether mod version 1.20.1-1.0.4 is installed
3. Start the server and have players join
4. Equip a player with the Stratus Armor from the Deep Aether mod
5. Attempt to take damage while wearing the Stratus Armor

## Expected Behavior
The player wearing Stratus Armor should take damage normally without causing a server crash.

## Actual Behavior
The server crashes with a `ReportedException`, indicating a collision between an entity and a block. The root cause is an `AbstractMethodError` in the `DaArmorMaterials` class, which is missing an implementation of the `m_6082_()` method from the `ArmorMaterial` interface. This occurs specifically when a player wearing Stratus Armor attempts to take damage.

## Additional Context
- This issue occurs in a multiplayer server environment, not in single-player mode.
- The Medieval MC [FORGE] - MMC4 modpack includes multiple mods that may be interacting with each other.
- The problem is specifically tied to the Stratus Armor from the Deep Aether mod version 1.20.1-1.0.4.
- Neruina is kicking players due to a ticking exception when the damage calculation fails for a player wearing Stratus Armor.
- This error prevents normal gameplay and causes frequent server crashes when players use Stratus Armor.

**Comment by TunefulTurnip** [comment]
This issue has already been resolved in version 1.3.2 of Deeper and Darker. Please update your modpack before filing a bug report and report the issue on the modpack's issue page if the issue still occurs.
